import { createClient } from "https://esm.sh/@supabase/supabase-js@2.98.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const { bot_id } = await req.json();
    if (!bot_id) {
      return new Response(JSON.stringify({ error: "bot_id required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const adminClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: bot } = await adminClient.from("bots").select("*").eq("id", bot_id).eq("user_id", user.id).single();
    if (!bot) {
      return new Response(JSON.stringify({ error: "Bot not found" }), { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    // Load commands
    const { data: commands } = await adminClient.from("commands").select("*").eq("bot_id", bot_id).eq("enabled", true);

    // Load modules
    const { data: modules } = await adminClient.from("bot_modules").select("*").eq("bot_id", bot_id).eq("enabled", true);

    // Load leveling config
    const { data: levelingConfig } = await adminClient.from("leveling_config").select("*").eq("bot_id", bot_id).maybeSingle();

    // Load welcome/moderation modules
    const statusModule = modules?.find((m: any) => m.module_name === "custom_status");
    const statusConfig = (statusModule?.config as any) || {};
    const welcomeModule = modules?.find((m: any) => m.module_name === "welcome");
    const automodModule = modules?.find((m: any) => m.module_name === "automod");

    const slashCommands = (commands || []).filter((c: any) => c.type === "slash");
    const prefixCommands = (commands || []).filter((c: any) => c.type === "prefix");

    // Generate Python script
    let script = `#!/usr/bin/env python3
"""
ArcBot Export — ${bot.bot_name}
Generated by ArcBot Dashboard
Install: pip install discord.py
Run: python bot.py
"""

import discord
from discord.ext import commands
from discord import app_commands
import asyncio
import os

# ─── Configuration ───────────────────────────────────────────────
TOKEN = os.environ.get("DISCORD_TOKEN", "YOUR_BOT_TOKEN_HERE")
PREFIX = "${bot.prefix || "!"}"

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix=PREFIX, intents=intents)

`;

    // Leveling system
    if (levelingConfig?.enabled) {
      script += `# ─── Leveling System ──────────────────────────────────────────────
user_xp = {}  # {user_id: {"xp": int, "level": int}}
XP_PER_MESSAGE = ${levelingConfig.xp_per_message || 15}
XP_COOLDOWN = ${levelingConfig.xp_cooldown || 60}
xp_cooldowns = {}

LEVEL_UP_MESSAGE = "${(levelingConfig.level_up_message || "Congratulations {user}, you reached level {level}!").replace(/"/g, '\\"')}"

ROLE_REWARDS = ${JSON.stringify(levelingConfig.role_rewards || [])}

def xp_for_level(level):
    return 5 * level * level + 50 * level + 100

`;
    }

    // Bot ready event
    script += `# ─── Events ──────────────────────────────────────────────────────
@bot.event
async def on_ready():
    print(f"✅ {bot.user.name} is online! (ID: {bot.user.id})")
    print(f"   Servers: {len(bot.guilds)}")
`;

    // Custom status
    if (statusConfig.status_text) {
      const actType = ["discord.ActivityType.playing", "discord.ActivityType.streaming", "discord.ActivityType.listening", "discord.ActivityType.watching", "discord.ActivityType.playing", "discord.ActivityType.competing"][statusConfig.activity_type || 0];
      const presMap: Record<string, string> = { online: "discord.Status.online", idle: "discord.Status.idle", dnd: "discord.Status.dnd", invisible: "discord.Status.invisible" };
      const pres = presMap[statusConfig.presence_status || "online"] || "discord.Status.online";
      script += `    await bot.change_presence(
        status=${pres},
        activity=discord.Activity(type=${actType}, name="${statusConfig.status_text.replace(/"/g, '\\"')}")
    )
`;
    }

    script += `    try:
        synced = await bot.tree.sync()
        print(f"   Synced {len(synced)} slash commands")
    except Exception as e:
        print(f"   Failed to sync commands: {e}")

`;

    // Welcome module
    if (welcomeModule) {
      const wConfig = (welcomeModule.config as any) || {};
      script += `@bot.event
async def on_member_join(member):
    """Welcome new members"""
    channel = member.guild.system_channel
    if channel:
        msg = "${(wConfig.message || "Welcome {user} to {server}!").replace(/"/g, '\\"')}"
        msg = msg.replace("{user}", member.mention).replace("{server}", member.guild.name)
        await channel.send(msg)

`;
    }

    // Leveling on_message
    if (levelingConfig?.enabled) {
      script += `@bot.event
async def on_message(message):
    if message.author.bot:
        return
    await bot.process_commands(message)

    # XP handling
    import time
    uid = str(message.author.id)
    now = time.time()
    if uid in xp_cooldowns and now - xp_cooldowns[uid] < XP_COOLDOWN:
        return
    xp_cooldowns[uid] = now

    if uid not in user_xp:
        user_xp[uid] = {"xp": 0, "level": 1}

    user_xp[uid]["xp"] += XP_PER_MESSAGE
    old_level = user_xp[uid]["level"]
    while user_xp[uid]["xp"] >= xp_for_level(user_xp[uid]["level"]):
        user_xp[uid]["xp"] -= xp_for_level(user_xp[uid]["level"])
        user_xp[uid]["level"] += 1

    if user_xp[uid]["level"] > old_level:
        msg = LEVEL_UP_MESSAGE.replace("{user}", message.author.mention).replace("{level}", str(user_xp[uid]["level"]))
        await message.channel.send(msg)
        # Role rewards
        for reward in ROLE_REWARDS:
            if reward.get("level") == user_xp[uid]["level"] and reward.get("role_id"):
                role = message.guild.get_role(int(reward["role_id"]))
                if role:
                    try:
                        await message.author.add_roles(role)
                    except:
                        pass

`;
    }

    // Slash commands
    if (slashCommands.length > 0) {
      script += `# ─── Slash Commands ──────────────────────────────────────────────\n`;
      for (const cmd of slashCommands) {
        const name = cmd.name.replace(/^\//, "").replace(/[^a-z0-9_]/g, "");
        const desc = (cmd.description || "No description").replace(/"/g, '\\"');
        const responses = (cmd.responses as any[]) || [];
        const content = responses.length > 0 ? (responses[0]?.content || "Command executed!").replace(/"/g, '\\"') : "Command executed!";

        script += `@bot.tree.command(name="${name}", description="${desc}")
async def cmd_${name}(interaction: discord.Interaction):
    await interaction.response.send_message("${content}"${cmd.ephemeral ? ", ephemeral=True" : ""})

`;
      }
    }

    // Prefix commands
    if (prefixCommands.length > 0) {
      script += `# ─── Prefix Commands ─────────────────────────────────────────────\n`;
      for (const cmd of prefixCommands) {
        const name = cmd.name.replace(/^[!\/]/, "").replace(/[^a-z0-9_]/g, "");
        const responses = (cmd.responses as any[]) || [];
        const content = responses.length > 0 ? (responses[0]?.content || "Command executed!").replace(/"/g, '\\"') : "Command executed!";

        script += `@bot.command(name="${name}")
async def pcmd_${name}(ctx):
    await ctx.send("${content}")

`;
      }
    }

    // Automod
    if (automodModule) {
      const aConfig = (automodModule.config as any) || {};
      const wordList = (aConfig.word_list as string[]) || [];
      if (wordList.length > 0) {
        script += `# ─── Auto-Moderation ─────────────────────────────────────────────
BANNED_WORDS = ${JSON.stringify(wordList)}

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    content_lower = message.content.lower()
    for word in BANNED_WORDS:
        if word.lower() in content_lower:
            await message.delete()
            await message.channel.send(f"{message.author.mention} your message was removed for containing a banned word.", delete_after=5)
            break
    await bot.process_commands(message)

`;
      }
    }

    // Leaderboard command if leveling enabled
    if (levelingConfig?.enabled) {
      script += `@bot.tree.command(name="leaderboard", description="View the XP leaderboard")
async def cmd_leaderboard(interaction: discord.Interaction):
    sorted_users = sorted(user_xp.items(), key=lambda x: x[1]["xp"], reverse=True)[:10]
    if not sorted_users:
        await interaction.response.send_message("No XP data yet!", ephemeral=True)
        return
    embed = discord.Embed(title="🏆 XP Leaderboard", color=discord.Color.gold())
    for i, (uid, data) in enumerate(sorted_users):
        medal = ["🥇", "🥈", "🥉"][i] if i < 3 else f"#{i+1}"
        embed.add_field(name=f"{medal} <@{uid}>", value=f"Level {data['level']} • {data['xp']} XP", inline=False)
    await interaction.response.send_message(embed=embed)

`;
    }

    // Run
    script += `# ─── Run ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Starting ${bot.bot_name}...")
    print("Make sure to set your DISCORD_TOKEN environment variable!")
    print("Or replace YOUR_BOT_TOKEN_HERE in the script.")
    bot.run(TOKEN)
`;

    return new Response(JSON.stringify({ script, filename: `${bot.bot_name.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase()}_bot.py` }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
