import { createClient } from "https://esm.sh/@supabase/supabase-js@2.98.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const { bot_id } = await req.json();
    if (!bot_id) {
      return new Response(JSON.stringify({ error: "bot_id required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const adminClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: bot } = await adminClient.from("bots").select("*").eq("id", bot_id).eq("user_id", user.id).single();
    if (!bot) {
      return new Response(JSON.stringify({ error: "Bot not found" }), { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    // Load commands
    const { data: commands } = await adminClient.from("commands").select("*").eq("bot_id", bot_id).eq("enabled", true);

    // Load modules
    const { data: modules } = await adminClient.from("bot_modules").select("*").eq("bot_id", bot_id).eq("enabled", true);

    // Load leveling config
    const { data: levelingConfig } = await adminClient.from("leveling_config").select("*").eq("bot_id", bot_id).maybeSingle();

    // Load welcome/moderation modules
    const statusModule = modules?.find((m: any) => m.module_name === "custom_status");
    const statusConfig = (statusModule?.config as any) || {};
    const welcomeModule = modules?.find((m: any) => m.module_name === "welcome");
    const automodModule = modules?.find((m: any) => m.module_name === "automod");
    const musicModule = modules?.find((m: any) => m.module_name === "music");
    const musicConfig = (musicModule?.config as any) || {};
    const autoResponderModule = modules?.find((m: any) => m.module_name === "auto_responder");
    const autoResponderConfig = (autoResponderModule?.config as any) || {};
    const giveawayModule = modules?.find((m: any) => m.module_name === "giveaways");
    const giveawayConfig = (giveawayModule?.config as any) || {};
    const pollModule = modules?.find((m: any) => m.module_name === "polls");

    const slashCommands = (commands || []).filter((c: any) => c.type === "slash");
    const prefixCommands = (commands || []).filter((c: any) => c.type === "prefix");

    // Generate Python script
    let script = `#!/usr/bin/env python3
"""
ArcBot Export — ${bot.bot_name}
Generated by ArcBot Dashboard
Install: pip install discord.py
Run: python bot.py
"""

import discord
from discord.ext import commands
from discord import app_commands
import asyncio
import os

# ─── Configuration ───────────────────────────────────────────────
TOKEN = os.environ.get("DISCORD_TOKEN", "YOUR_BOT_TOKEN_HERE")
PREFIX = "${bot.prefix || "!"}"

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix=PREFIX, intents=intents)

`;

    // Leveling system
    if (levelingConfig?.enabled) {
      script += `# ─── Leveling System ──────────────────────────────────────────────
user_xp = {}  # {user_id: {"xp": int, "level": int}}
XP_PER_MESSAGE = ${levelingConfig.xp_per_message || 15}
XP_COOLDOWN = ${levelingConfig.xp_cooldown || 60}
xp_cooldowns = {}

LEVEL_UP_MESSAGE = "${(levelingConfig.level_up_message || "Congratulations {user}, you reached level {level}!").replace(/"/g, '\\"')}"

ROLE_REWARDS = ${JSON.stringify(levelingConfig.role_rewards || [])}

def xp_for_level(level):
    return 5 * level * level + 50 * level + 100

`;
    }

    // Bot ready event
    script += `# ─── Events ──────────────────────────────────────────────────────
@bot.event
async def on_ready():
    print(f"✅ {bot.user.name} is online! (ID: {bot.user.id})")
    print(f"   Servers: {len(bot.guilds)}")
`;

    // Custom status
    if (statusConfig.status_text) {
      const actType = ["discord.ActivityType.playing", "discord.ActivityType.streaming", "discord.ActivityType.listening", "discord.ActivityType.watching", "discord.ActivityType.playing", "discord.ActivityType.competing"][statusConfig.activity_type || 0];
      const presMap: Record<string, string> = { online: "discord.Status.online", idle: "discord.Status.idle", dnd: "discord.Status.dnd", invisible: "discord.Status.invisible" };
      const pres = presMap[statusConfig.presence_status || "online"] || "discord.Status.online";
      script += `    await bot.change_presence(
        status=${pres},
        activity=discord.Activity(type=${actType}, name="${statusConfig.status_text.replace(/"/g, '\\"')}")
    )
`;
    }

    script += `    try:
        synced = await bot.tree.sync()
        print(f"   Synced {len(synced)} slash commands")
    except Exception as e:
        print(f"   Failed to sync commands: {e}")

`;

    // Welcome module
    if (welcomeModule) {
      const wConfig = (welcomeModule.config as any) || {};
      script += `@bot.event
async def on_member_join(member):
    """Welcome new members"""
    channel = member.guild.system_channel
    if channel:
        msg = "${(wConfig.message || "Welcome {user} to {server}!").replace(/"/g, '\\"')}"
        msg = msg.replace("{user}", member.mention).replace("{server}", member.guild.name)
        await channel.send(msg)

`;
    }

    // Leveling on_message
    if (levelingConfig?.enabled) {
      script += `@bot.event
async def on_message(message):
    if message.author.bot:
        return
    await bot.process_commands(message)

    # XP handling
    import time
    uid = str(message.author.id)
    now = time.time()
    if uid in xp_cooldowns and now - xp_cooldowns[uid] < XP_COOLDOWN:
        return
    xp_cooldowns[uid] = now

    if uid not in user_xp:
        user_xp[uid] = {"xp": 0, "level": 1}

    user_xp[uid]["xp"] += XP_PER_MESSAGE
    old_level = user_xp[uid]["level"]
    while user_xp[uid]["xp"] >= xp_for_level(user_xp[uid]["level"]):
        user_xp[uid]["xp"] -= xp_for_level(user_xp[uid]["level"])
        user_xp[uid]["level"] += 1

    if user_xp[uid]["level"] > old_level:
        msg = LEVEL_UP_MESSAGE.replace("{user}", message.author.mention).replace("{level}", str(user_xp[uid]["level"]))
        await message.channel.send(msg)
        # Role rewards
        for reward in ROLE_REWARDS:
            if reward.get("level") == user_xp[uid]["level"] and reward.get("role_id"):
                role = message.guild.get_role(int(reward["role_id"]))
                if role:
                    try:
                        await message.author.add_roles(role)
                    except:
                        pass

`;
    }

    // Slash commands
    if (slashCommands.length > 0) {
      script += `# ─── Slash Commands ──────────────────────────────────────────────\n`;
      for (const cmd of slashCommands) {
        const name = cmd.name.replace(/^\//, "").replace(/[^a-z0-9_]/g, "");
        const desc = (cmd.description || "No description").replace(/"/g, '\\"');
        const responses = (cmd.responses as any[]) || [];
        const content = responses.length > 0 ? (responses[0]?.content || "Command executed!").replace(/"/g, '\\"') : "Command executed!";

        script += `@bot.tree.command(name="${name}", description="${desc}")
async def cmd_${name}(interaction: discord.Interaction):
    await interaction.response.send_message("${content}"${cmd.ephemeral ? ", ephemeral=True" : ""})

`;
      }
    }

    // Prefix commands
    if (prefixCommands.length > 0) {
      script += `# ─── Prefix Commands ─────────────────────────────────────────────\n`;
      for (const cmd of prefixCommands) {
        const name = cmd.name.replace(/^[!\/]/, "").replace(/[^a-z0-9_]/g, "");
        const responses = (cmd.responses as any[]) || [];
        const content = responses.length > 0 ? (responses[0]?.content || "Command executed!").replace(/"/g, '\\"') : "Command executed!";

        script += `@bot.command(name="${name}")
async def pcmd_${name}(ctx):
    await ctx.send("${content}")

`;
      }
    }

    // Automod
    if (automodModule) {
      const aConfig = (automodModule.config as any) || {};
      const wordList = (aConfig.word_list as string[]) || [];
      if (wordList.length > 0) {
        script += `# ─── Auto-Moderation ─────────────────────────────────────────────
BANNED_WORDS = ${JSON.stringify(wordList)}

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    content_lower = message.content.lower()
    for word in BANNED_WORDS:
        if word.lower() in content_lower:
            await message.delete()
            await message.channel.send(f"{message.author.mention} your message was removed for containing a banned word.", delete_after=5)
            break
    await bot.process_commands(message)

`;
      }
    }

    // Leaderboard command if leveling enabled
    if (levelingConfig?.enabled) {
      script += `@bot.tree.command(name="leaderboard", description="View the XP leaderboard")
async def cmd_leaderboard(interaction: discord.Interaction):
    sorted_users = sorted(user_xp.items(), key=lambda x: x[1]["xp"], reverse=True)[:10]
    if not sorted_users:
        await interaction.response.send_message("No XP data yet!", ephemeral=True)
        return
    embed = discord.Embed(title="🏆 XP Leaderboard", color=discord.Color.gold())
    for i, (uid, data) in enumerate(sorted_users):
        medal = ["🥇", "🥈", "🥉"][i] if i < 3 else f"#{i+1}"
        embed.add_field(name=f"{medal} <@{uid}>", value=f"Level {data['level']} • {data['xp']} XP", inline=False)
    await interaction.response.send_message(embed=embed)

`;
    }

    // Auto-responder
    if (autoResponderModule?.enabled && autoResponderConfig.responses?.length > 0) {
      script += `# ─── Auto Responder ──────────────────────────────────────────────
AUTO_RESPONSES = ${JSON.stringify(autoResponderConfig.responses.map((r: any) => ({ trigger: r.trigger, response: r.response, matchType: r.matchType, ignoreCase: r.ignoreCase, deleteOriginal: r.deleteOriginal })))}

@bot.listen("on_message")
async def auto_respond(message):
    if message.author.bot:
        return
    content = message.content
    for ar in AUTO_RESPONSES:
        trigger = ar["trigger"]
        msg_text = content.lower() if ar.get("ignoreCase") else content
        trig_text = trigger.lower() if ar.get("ignoreCase") else trigger
        matched = False
        if ar.get("matchType") == "exact":
            matched = msg_text == trig_text
        elif ar.get("matchType") == "startsWith":
            matched = msg_text.startswith(trig_text)
        elif ar.get("matchType") == "regex":
            import re
            try:
                matched = bool(re.search(trigger, content, re.IGNORECASE if ar.get("ignoreCase") else 0))
            except:
                pass
        else:
            matched = trig_text in msg_text
        if matched:
            reply = ar["response"].replace("{user}", message.author.mention).replace("{server}", message.guild.name if message.guild else "DM").replace("{channel}", message.channel.name if hasattr(message.channel, "name") else "DM")
            await message.channel.send(reply)
            if ar.get("deleteOriginal"):
                try:
                    await message.delete()
                except:
                    pass
            break

`;
    }

    // Music module
    if (musicModule?.enabled) {
      script += `# ─── Music Module ────────────────────────────────────────────────
# Requires: pip install discord.py[voice] yt-dlp
import yt_dlp

FFMPEG_OPTIONS = {"options": "-vn"}
YDL_OPTIONS = {"format": "bestaudio/best", "noplaylist": True, "quiet": True}

music_queues = {}  # guild_id -> list of songs

@bot.tree.command(name="play", description="Play a song from YouTube")
@app_commands.describe(query="Song name or YouTube URL")
async def cmd_play(interaction: discord.Interaction, query: str):
    if not interaction.user.voice:
        await interaction.response.send_message("❌ Join a voice channel first!", ephemeral=True)
        return
    await interaction.response.defer()
    vc = interaction.guild.voice_client
    if not vc:
        vc = await interaction.user.voice.channel.connect()
    with yt_dlp.YoutubeDL(YDL_OPTIONS) as ydl:
        if not query.startswith("http"):
            query = f"ytsearch:{query}"
        info = ydl.extract_info(query, download=False)
        if "entries" in info:
            info = info["entries"][0]
        url = info["url"]
        title = info.get("title", "Unknown")
    gid = str(interaction.guild_id)
    if gid not in music_queues:
        music_queues[gid] = []
    if vc.is_playing():
        music_queues[gid].append({"url": url, "title": title})
        await interaction.followup.send(f"📋 Added to queue: **{title}**")
    else:
        vc.play(discord.FFmpegPCMAudio(url, **FFMPEG_OPTIONS), after=lambda e: asyncio.run_coroutine_threadsafe(play_next(interaction.guild), bot.loop))
        vc.source = discord.PCMVolumeTransformer(vc.source, volume=${(musicConfig.defaultVolume || 50) / 100})
        await interaction.followup.send(f"🎶 Now playing: **{title}**")

async def play_next(guild):
    gid = str(guild.id)
    vc = guild.voice_client
    if not vc or gid not in music_queues or not music_queues[gid]:
        return
    song = music_queues[gid].pop(0)
    vc.play(discord.FFmpegPCMAudio(song["url"], **FFMPEG_OPTIONS), after=lambda e: asyncio.run_coroutine_threadsafe(play_next(guild), bot.loop))

@bot.tree.command(name="skip", description="Skip the current song")
async def cmd_skip(interaction: discord.Interaction):
    vc = interaction.guild.voice_client
    if vc and vc.is_playing():
        vc.stop()
        await interaction.response.send_message("⏭️ Skipped!")
    else:
        await interaction.response.send_message("Nothing is playing.", ephemeral=True)

@bot.tree.command(name="stop", description="Stop music and disconnect")
async def cmd_stop(interaction: discord.Interaction):
    vc = interaction.guild.voice_client
    if vc:
        music_queues.pop(str(interaction.guild_id), None)
        await vc.disconnect()
        await interaction.response.send_message("⏹️ Stopped and disconnected.")
    else:
        await interaction.response.send_message("Not connected.", ephemeral=True)

@bot.tree.command(name="queue", description="View the music queue")
async def cmd_queue(interaction: discord.Interaction):
    gid = str(interaction.guild_id)
    q = music_queues.get(gid, [])
    if not q:
        await interaction.response.send_message("Queue is empty.", ephemeral=True)
        return
    desc = "\\n".join([f"{i+1}. {s['title']}" for i, s in enumerate(q[:10])])
    embed = discord.Embed(title="🎵 Queue", description=desc, color=discord.Color.blue())
    if len(q) > 10:
        embed.set_footer(text=f"and {len(q) - 10} more...")
    await interaction.response.send_message(embed=embed)

@bot.tree.command(name="pause", description="Pause the current song")
async def cmd_pause(interaction: discord.Interaction):
    vc = interaction.guild.voice_client
    if vc and vc.is_playing():
        vc.pause()
        await interaction.response.send_message("⏸️ Paused.")
    else:
        await interaction.response.send_message("Nothing to pause.", ephemeral=True)

@bot.tree.command(name="resume", description="Resume the paused song")
async def cmd_resume(interaction: discord.Interaction):
    vc = interaction.guild.voice_client
    if vc and vc.is_paused():
        vc.resume()
        await interaction.response.send_message("▶️ Resumed.")
    else:
        await interaction.response.send_message("Nothing to resume.", ephemeral=True)

@bot.tree.command(name="volume", description="Set the volume")
@app_commands.describe(level="Volume level (1-100)")
async def cmd_volume(interaction: discord.Interaction, level: int):
    vc = interaction.guild.voice_client
    if vc and vc.source:
        vc.source.volume = level / 100
        await interaction.response.send_message(f"🔊 Volume set to {level}%")
    else:
        await interaction.response.send_message("Nothing is playing.", ephemeral=True)

`;
    }

    // Giveaway
    if (giveawayModule?.enabled) {
      script += `# ─── Giveaways ───────────────────────────────────────────────────
import random as _random

@bot.tree.command(name="giveaway", description="Start a giveaway")
@app_commands.describe(prize="What are you giving away?", duration="Duration in seconds", winners="Number of winners")
async def cmd_giveaway(interaction: discord.Interaction, prize: str, duration: int = 86400, winners: int = 1):
    embed = discord.Embed(title="🎉 GIVEAWAY 🎉", description=f"Prize: **{prize}**\\nReact with 🎉 to enter!\\nWinners: {winners}\\nEnds in {duration}s", color=discord.Color.gold())
    await interaction.response.send_message(embed=embed)
    msg = await interaction.original_response()
    await msg.add_reaction("🎉")
    await asyncio.sleep(duration)
    msg = await interaction.channel.fetch_message(msg.id)
    reaction = discord.utils.get(msg.reactions, emoji="🎉")
    if reaction:
        users = [u async for u in reaction.users() if not u.bot]
        if users:
            chosen = _random.sample(users, min(winners, len(users)))
            winners_text = ", ".join([w.mention for w in chosen])
            await interaction.channel.send(f"🎉 Congratulations {winners_text}! You won **{prize}**!")
        else:
            await interaction.channel.send("No one entered the giveaway. 😢")

`;
    }

    // Run
    script += `# ─── Run ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Starting ${bot.bot_name}...")
    print("Make sure to set your DISCORD_TOKEN environment variable!")
    print("Or replace YOUR_BOT_TOKEN_HERE in the script.")
    bot.run(TOKEN)
`;

    return new Response(JSON.stringify({ script, filename: `${bot.bot_name.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase()}_bot.py` }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
